name: Build and Release

on:
  push:
    branches:
      - aterna/gitversioning

jobs:
  tag-release:
    name: Generate Release
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ variables.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.2.1
        with:
          versionSpec: '5.12.0'
      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.2.1
        with:
          useConfigFile: true
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.gitversion.outputs.semVer }}
          name: Release ${{ steps.gitversion.outputs.semVer }}
          generate_release_notes: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
