name: Build and (Pre)Release

on:
  push:
    branches:
      - main
      - develop/**

permissions:
  contents: read
  packages: write # Permissions for the GitHub Actions token to push image to registry

jobs:
  build-image:
    name: Generate Release
    runs-on: ubuntu-latest
    needs: tag-release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/model-service:latest
            ghcr.io/${{ github.repository_owner }}/model-service:${{ needs.tag-release.outputs.tag }}
          build-args: |
            MODEL_SERVICE_VERSION=${{ needs.tag-release.outputs.tag }}
  tag-release:
    name: Generate Release
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Create GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          persist-credentials: false
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.2.1
        with:
          versionSpec: '5.12.0'
      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.2.1
        with:
          useConfigFile: true
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          tag_name: ${{ steps.gitversion.outputs.semVer }}
          name: Release ${{ steps.gitversion.outputs.semVer }}
          generate_release_notes: true
          prerelease: ${{ contains(steps.gitversion.outputs.semVer, '-') }}
        
